import type { Metadata } from "next";
import { Fugaz_One, Play } from "next/font/google";
import "./globals.css";

const ZenDots = Fugaz_One({
  weight: "400",
  subsets: ["latin"],
});

const PlayFont = Play({
  weight: "400",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ZenDots.className} ${PlayFont.className}` }>
        <div className="hidden md:block">
          {children}
        </div>
        <div className="Alert min-h-screen flex justify-center items-center animated-bg">
        <h1 className="text-5xl text-center px-4 flex justify-center items-center flex-col">
  Please open in browser
  <span className=" w-4 h-4 min-w-[14px] min-h-[14px] rounded-full bg-white animate-blink"></span>
</h1>



        </div>
      </body>
    </html>
  );
}
